version: 0.0
os: linux

files:
  - source: /miniproject4-next
    destination: /home/ubuntu/app/miniproject4-next
    overwrite: true

permissions:
  - object: /home/ubuntu/app/miniproject4-next
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
      - file

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 180
      runas: ubuntu